# Generated by Django 3.0.7 on 2020-08-15 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.Product')),
            ],
        ),
    ]
